# Generated by Django 3.0.8 on 2020-11-03 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=120, verbose_name='Name')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=120, verbose_name='Title')),
                ('description', models.CharField(blank=True, default='', max_length=512, verbose_name='Description')),
                ('is_public', models.BooleanField(blank=True, default=True, help_text='Designates whether this wishlist should be treated as public. Any todify user can view a public wishlist.', verbose_name='Visibility Status')),
            ],
            options={
                'verbose_name': 'wishlist',
                'verbose_name_plural': 'wishlists',
                'db_table': 'wishlist',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WishlistCategoryMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlists.Category')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlists.Wishlist')),
            ],
            options={
                'verbose_name': 'wishlist_category_mapping',
                'verbose_name_plural': 'wishlist_category_mappings',
                'db_table': 'wishlist_category_mapping',
                'ordering': ('-created_at',),
                'unique_together': {('wishlist', 'category')},
            },
        ),
        migrations.AddField(
            model_name='wishlist',
            name='categories',
            field=models.ManyToManyField(related_name='wishlists', through='wishlists.WishlistCategoryMapping', to='wishlists.Category'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
