# Generated by Django 3.0.8 on 2020-11-03 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import uuid_upload_path.storage
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wishlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=120, verbose_name='Title')),
                ('description', models.CharField(blank=True, default='', max_length=512, verbose_name='Description')),
                ('link', models.URLField(blank=True, default='', verbose_name='Link')),
                ('photo', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=uuid_upload_path.storage.upload_to, verbose_name='Photo')),
                ('photo_poi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name="Photo's Point of Interest")),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='wishlists.Wishlist')),
            ],
            options={
                'verbose_name': 'card',
                'verbose_name_plural': 'cards',
                'db_table': 'card',
                'ordering': ('-created_at',),
            },
        ),
    ]
